file_format: "1"
id: dactyl_m6x6
Name: dactyl_m6x6
type: shield
url: https://github.com/bullwinkle3000/zmk-config-xiao/
requires:
  - nice_nano_v2
exposes: 
  - i2c_oled
features:
  - keys
  - display
  - encoders
siblings:
  - dactyl_m6x6_left
  - dactyl_m6x6_right
